os:
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode8
script:
  - swift build
  - swift test
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    on_success: never
    on_failure: change